In [1]:
import pandas as pd

In [2]:
churn_data=pd.read_csv("churn_data.csv")
customer_data=pd.read_csv("customer_data.csv")
internet_data=pd.read_csv("internet_data.csv")

In [3]:
churn_data.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
customer_data.head()

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [5]:
internet_data.head()

,customerID,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,No,Fiber optic,No,No,No,No,No,No

In [6]:
df=pd.merge(churn_data,customer_data,how="inner",on="customerID")

In [7]:
telecom_data=pd.merge(df,internet_data,how="inner",on="customerID")
telecom_data.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender,...,Partner,Dependents,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,Female,...,Yes,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No,Male,...,No,No,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Male,...,No,No,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,Male,...,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Female,...,No,No,No,Fiber optic,No,No,No,No,No,No

In [8]:
telecom_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [9]:
telecom_data.PhoneService=telecom_data.PhoneService.map({"Yes":1,"No":0})
telecom_data.PaperlessBilling=telecom_data.PaperlessBilling.map({"Yes":1,"No":0})
telecom_data.Churn=telecom_data.Churn.map({"Yes":1,"No":0})
telecom_data.Partner=telecom_data.Partner.map({"Yes":1,"No":0})
telecom_data.Dependents=telecom_data.Dependents.map({"Yes":1,"No":0})

In [10]:
contact=pd.get_dummies(telecom_data["Contract"],prefix="Contract",drop_first=True)
telecom_data=pd.concat([telecom_data,contact],axis=1)


pay=pd.get_dummies(telecom_data.PaymentMethod,prefix="PaymentMethod",drop_first=True)
telecom_data=pd.concat([telecom_data,pay],axis=1)

gen=pd.get_dummies(telecom_data.gender,prefix="gender",drop_first=True)
telecom_data=pd.concat([telecom_data,gen],axis=1)

mul_lines=pd.get_dummies(telecom_data.MultipleLines,prefix="MultipleLines",drop_first=True)
telecom_data=pd.concat([telecom_data,mul_lines],axis=1)

internet_service=pd.get_dummies(telecom_data.InternetService,prefix="InternetService",drop_first=True)
telecom_data=pd.concat([telecom_data,internet_service],axis=1)

online_security=pd.get_dummies(telecom_data.OnlineSecurity,prefix="OnlineSecurity",drop_first=True)
telecom_data=pd.concat([telecom_data,online_security],axis=1)

online_backup=pd.get_dummies(telecom_data.OnlineBackup,prefix="OnlineBackup",drop_first=True)
telecom_data=pd.concat([telecom_data,online_backup],axis=1)


device_protection=pd.get_dummies(telecom_data.DeviceProtection,prefix="DeviceProtection",drop_first=True)
telecom_data=pd.concat([telecom_data,device_protection],axis=1)

tech_support=pd.get_dummies(telecom_data.TechSupport,prefix="TechSupport",drop_first=True)
telecom_data=pd.concat([telecom_data,tech_support],axis=1)


streaming_tv=pd.get_dummies(telecom_data.StreamingTV,prefix="StreamingTV",drop_first=True)
telecom_data=pd.concat([telecom_data,streaming_tv],axis=1)


streaming_movies=pd.get_dummies(telecom_data.StreamingMovies,prefix="StreamingMovies",drop_first=True)
telecom_data=pd.concat([telecom_data,streaming_movies],axis=1)

In [11]:
telecom_data=telecom_data.drop(["Contract","PaymentMethod","gender",
                               "MultipleLines","InternetService","OnlineSecurity",
                               "OnlineBackup","DeviceProtection","TechSupport",
                                "StreamingTV","StreamingMovies"],1)

In [12]:
telecom_data.TotalCharges=telecom_data.TotalCharges.convert_objects(convert_numeric=True)
telecom_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 32 columns):
customerID                               7043 non-null object
tenure                                   7043 non-null int64
PhoneService                             7043 non-null int64
PaperlessBilling                         7043 non-null int64
MonthlyCharges                           7043 non-null float64
TotalCharges                             7032 non-null float64
Churn                                    7043 non-null int64
SeniorCitizen                            7043 non-null int64
Partner                                  7043 non-null int64
Dependents                               7043 non-null int64
Contract_One year                        7043 non-null uint8
Contract_Two year                        7043 non-null uint8
PaymentMethod_Credit card (automatic)    7043 non-null uint8
PaymentMethod_Electronic check           7043 non-null uint8
PaymentMethod_Mailed check               7043 non-null uint8
gender_Male                              7043 non-null uint8
MultipleLines_No phone service           7043 non-null uint8
MultipleLines_Yes                        7043 non-null uint8
InternetService_Fiber optic              7043 non-null uint8
InternetService_No                       7043 non-null uint8
OnlineSecurity_No internet service       7043 non-null uint8
OnlineSecurity_Yes                       7043 non-null uint8
OnlineBackup_No internet service         7043 non-null uint8
OnlineBackup_Yes                         7043 non-null uint8
DeviceProtection_No internet service     7043 non-null uint8
DeviceProtection_Yes                     7043 non-null uint8
TechSupport_No internet service          7043 non-null uint8
TechSupport_Yes                          7043 non-null uint8
StreamingTV_No internet service          7043 non-null uint8
StreamingTV_Yes                          7043 non-null uint8
StreamingMovies_No internet service      7043 non-null uint8
StreamingMovies_Yes                      7043 non-null uint8
dtypes: float64(2), int64(7), object(1), uint8(22)
memory usage: 756.6+ KB

/home/abhi/venvs/notebook/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.

In [13]:
num_coloumns=telecom_data[["tenure","MonthlyCharges","SeniorCitizen","TotalCharges"]]
num_coloumns.describe(percentiles=[0.25,0.50,0.90,0.95,.99])

            tenure  MonthlyCharges  SeniorCitizen  TotalCharges
count  7043.000000     7043.000000    7043.000000   7032.000000
mean     32.371149       64.761692       0.162147   2283.300441
std      24.559481       30.090047       0.368612   2266.771362
min       0.000000       18.250000       0.000000     18.800000
25%       9.000000       35.500000       0.000000    401.450000
50%      29.000000       70.350000       0.000000   1397.475000
90%      69.000000      102.600000       1.000000   5976.640000
95%      72.000000      107.400000       1.000000   6923.590000
99%      72.000000      114.729000       1.000000   8039.883000
max      72.000000      118.750000       1.000000   8684.800000

In [14]:
telecom_data.isnull().sum()

customerID                                0
tenure                                    0
PhoneService                              0
PaperlessBilling                          0
MonthlyCharges                            0
TotalCharges                             11
Churn                                     0
SeniorCitizen                             0
Partner                                   0
Dependents                                0
Contract_One year                         0
Contract_Two year                         0
PaymentMethod_Credit card (automatic)     0
PaymentMethod_Electronic check            0
PaymentMethod_Mailed check                0
gender_Male                               0
MultipleLines_No phone service            0
MultipleLines_Yes                         0
InternetService_Fiber optic               0
InternetService_No                        0
OnlineSecurity_No internet service        0
OnlineSecurity_Yes                        0
OnlineBackup_No internet service          0
OnlineBackup_Yes                          0
DeviceProtection_No internet service      0
DeviceProtection_Yes                      0
TechSupport_No internet service           0
TechSupport_Yes                           0
StreamingTV_No internet service           0
StreamingTV_Yes                           0
StreamingMovies_No internet service       0
StreamingMovies_Yes                       0
dtype: int64

In [15]:
# round(100*(/len(telecom_data.index)),2)
telecom_data.isnull().sum()/len(telecom_data.index)*100

customerID                               0.000000
tenure                                   0.000000
PhoneService                             0.000000
PaperlessBilling                         0.000000
MonthlyCharges                           0.000000
TotalCharges                             0.156183
Churn                                    0.000000
SeniorCitizen                            0.000000
Partner                                  0.000000
Dependents                               0.000000
Contract_One year                        0.000000
Contract_Two year                        0.000000
PaymentMethod_Credit card (automatic)    0.000000
PaymentMethod_Electronic check           0.000000
PaymentMethod_Mailed check               0.000000
gender_Male                              0.000000
MultipleLines_No phone service           0.000000
MultipleLines_Yes                        0.000000
InternetService_Fiber optic              0.000000
InternetService_No                       0.000000
OnlineSecurity_No internet service       0.000000
OnlineSecurity_Yes                       0.000000
OnlineBackup_No internet service         0.000000
OnlineBackup_Yes                         0.000000
DeviceProtection_No internet service     0.000000
DeviceProtection_Yes                     0.000000
TechSupport_No internet service          0.000000
TechSupport_Yes                          0.000000
StreamingTV_No internet service          0.000000
StreamingTV_Yes                          0.000000
StreamingMovies_No internet service      0.000000
StreamingMovies_Yes                      0.000000
dtype: float64

In [16]:
import numpy as np
telecom_data=telecom_data[~np.isnan(telecom_data.TotalCharges)]

In [17]:
# standarization

df=telecom_data[["tenure","MonthlyCharges","TotalCharges"]]

In [18]:
standard_df=(df-df.mean())/df.std()

In [19]:
telecom_data=telecom_data.drop(["tenure","MonthlyCharges","TotalCharges"],1)

In [20]:
telecom_data=pd.concat([telecom_data,standard_df],1)

In [21]:
telecom_data.head()
telecome_col=list(telecom_data.columns)
telecome_col.pop(telecome_col.index("Churn"))
telecome_col.pop(telecome_col.index("customerID"))
# .pop("Churn")

# # telecom_data[telecome_col].iloc[:,10:20]
# telecom_data=telecom_data.dropna()

# from sklearn.feature_selection import RFE
# # RFE()
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(telecom_data[telecome_col],telecom_data.Churn,train_size=0.7,test_size=0.3,random_state=100)

/home/abhi/venvs/notebook/local/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [22]:
import statsmodels.api as sm

In [23]:
log_reg=sm.GLM(y_train,(sm.add_constant(X_train)),family=sm.families.Binomial())
log_reg.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 4922
Model:                            GLM   Df Residuals:                     4898
Model Family:                Binomial   Df Model:                           23
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2004.7
Date:                Sat, 30 Jun 2018   Deviance:                       4009.4
Time:                        19:18:23   Pearson chi2:                 6.07e+03
No. Iterations:                    68   Covariance Type:             nonrobust
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
const                                    -2.3056      0.773     -2.984      0.003      -3.820      -0.791
PhoneService                             -0.6775      0.090     -7.495      0.000      -0.855      -0.500
PaperlessBilling                          0.3254      0.090      3.614      0.000       0.149       0.502
SeniorCitizen                             0.3984      0.102      3.924      0.000       0.199       0.597
Partner                                   0.0374      0.094      0.399      0.690      -0.146       0.221
Dependents                               -0.1430      0.107     -1.332      0.183      -0.353       0.067
Contract_One year                        -0.6578      0.129     -5.106      0.000      -0.910      -0.405
Contract_Two year                        -1.2455      0.212     -5.874      0.000      -1.661      -0.830
PaymentMethod_Credit card (automatic)    -0.2577      0.137     -1.883      0.060      -0.526       0.011
PaymentMethod_Electronic check            0.1615      0.113      1.434      0.152      -0.059       0.382
PaymentMethod_Mailed check               -0.2536      0.137     -1.845      0.065      -0.523       0.016
gender_Male                              -0.0346      0.078     -0.442      0.658      -0.188       0.119
MultipleLines_No phone service           -1.6282      0.775     -2.100      0.036      -3.148      -0.108
MultipleLines_Yes                         0.5623      0.214      2.628      0.009       0.143       0.982
InternetService_Fiber optic               2.5124      0.967      2.599      0.009       0.618       4.407
InternetService_No                       -0.3970      0.140     -2.831      0.005      -0.672      -0.122
OnlineSecurity_No internet service       -0.3970      0.140     -2.831      0.005      -0.672      -0.122
OnlineSecurity_Yes                       -0.0245      0.216     -0.113      0.910      -0.448       0.399
OnlineBackup_No internet service         -0.3970      0.140     -2.831      0.005      -0.672      -0.122
OnlineBackup_Yes                          0.1740      0.212      0.822      0.411      -0.241       0.589
DeviceProtection_No internet service     -0.3970      0.140     -2.831      0.005      -0.672      -0.122
DeviceProtection_Yes                      0.3229      0.215      1.501      0.133      -0.099       0.744
TechSupport_No internet service          -0.3970      0.140     -2.831      0.005      -0.672      -0.122
TechSupport_Yes                          -0.0305      0.216     -0.141      0.888      -0.455       0.394
StreamingTV_No internet service          -0.3970      0.140     -2.831      0.005      -0.672      -0.122
StreamingTV_Yes                           0.9598      0.396      2.423      0.015       0.183       1.736
StreamingMovies_No internet service      -0.3970      0.140     -2.831      0.005      -0.672      -0.122
StreamingMovies_Yes                       0.8484      0.396      2.143      0.032       0.072       1.624
tenure                                   -1.5198      0.190     -8.015      0.000      -1.891      -1.148
MonthlyCharges                           -2.1817      1.160     -1.880      0.060      -4.456       0.092
TotalCharges                              0.7329      0.198      3.705      0.000       0.345       1.121
=========================================================================================================
"""

In [24]:
# First we import Logistic Regression from Sklearn library

from sklearn.linear_model import LogisticRegression

# Creating object for logistic regression

logreg = LogisticRegression()

# Importing RFE from Sklearn

from sklearn.feature_selection import RFE

# Running RFE with 13 variables as output
X=X_train
y=y_train
rfe = RFE(logreg, 10)
rfe = rfe.fit(X,y)

# Printing the selected variables rank and boolean values

print(rfe.support_)           # Printing the boolean results
print(rfe.ranking_)           # Printing the ranking

# X.describe
# y

[ True False  True False False  True  True False False False False False
 False  True False False  True False False  True False  True False False
 False False False  True False  True]
[ 1  5  1 20 16  1  1  3 13  2 19 12  9  1 15 14  1  6 11  1 21  1  4  8
  7 10 17  1 18  1]

In [25]:
col=X_train.columns[rfe.support_]

In [26]:
col

Index([u'PhoneService', u'SeniorCitizen', u'Contract_One year',
       u'Contract_Two year', u'InternetService_Fiber optic',
       u'OnlineSecurity_Yes', u'DeviceProtection_No internet service',
       u'TechSupport_No internet service', u'tenure', u'TotalCharges'],
      dtype='object')

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logsk=LogisticRegression()
logsk.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [28]:
log_reg2=sm.GLM(y_train,(sm.add_constant(X_train[col])),family=sm.families.Binomial())
log_reg2.fit().summary()
# log_reg2=log_reg2.fit()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  Churn   No. Observations:                 4922
Model:                            GLM   Df Residuals:                     4912
Model Family:                Binomial   Df Model:                            9
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2047.1
Date:                Sat, 30 Jun 2018   Deviance:                       4094.1
Time:                        19:18:24   Pearson chi2:                 6.41e+03
No. Iterations:                     7   Covariance Type:             nonrobust
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
const                                   -0.9093      0.143     -6.338      0.000      -1.191      -0.628
PhoneService                            -0.5458      0.156     -3.495      0.000      -0.852      -0.240
SeniorCitizen                            0.5226      0.098      5.355      0.000       0.331       0.714
Contract_One year                       -0.7811      0.125     -6.239      0.000      -1.026      -0.536
Contract_Two year                       -1.5004      0.208     -7.219      0.000      -1.908      -1.093
InternetService_Fiber optic              0.9964      0.112      8.908      0.000       0.777       1.216
OnlineSecurity_Yes                      -0.4929      0.100     -4.905      0.000      -0.690      -0.296
DeviceProtection_No internet service    -0.5327      0.079     -6.728      0.000      -0.688      -0.378
TechSupport_No internet service         -0.5327      0.079     -6.728      0.000      -0.688      -0.378
tenure                                  -1.5507      0.177     -8.756      0.000      -1.898      -1.204
TotalCharges                             0.8134      0.174      4.663      0.000       0.472       1.155
========================================================================================================
"""

In [29]:
# y_predict=log_reg2.predict(X_test[col])
# X_test[colm

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train[col],y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [30]:
y_predict=model.predict_proba(X_test[col])

In [31]:
y_predict_df=pd.DataFrame(y_predict)
y_pred_1=y_predict_df.iloc[:,[1]]

In [32]:
y_test_df=pd.DataFrame(y_test)

In [33]:
y_test_df["Customer_id"]=y_test_df.index
y_test_df.head()

      Churn  Customer_id
942       0          942
3730      1         3730
1761      0         1761
2283      1         2283
1872      0         1872

In [34]:
y_pred_1.reset_index()

      index         1
0         0  0.493557
1         1  0.324672
2         2  0.003127
3         3  0.675176
4         4  0.006907
5         5  0.630573
6         6  0.345483
7         7  0.003704
8         8  0.568031
9         9  0.140276
10       10  0.090718
11       11  0.121600
12       12  0.020564
13       13  0.560067
14       14  0.659180
15       15  0.664517
16       16  0.423366
17       17  0.660961
18       18  0.087554
19       19  0.080170
20       20  0.346721
21       21  0.676134
22       22  0.640550
23       23  0.475273
24       24  0.042111
25       25  0.002010
26       26  0.026655
27       27  0.003629
28       28  0.348920
29       29  0.216712
...     ...       ...
2080   2080  0.008117
2081   2081  0.420552
2082   2082  0.258171
2083   2083  0.010753
2084   2084  0.385874
2085   2085  0.197400
2086   2086  0.652636
2087   2087  0.407444
2088   2088  0.044505
2089   2089  0.355942
2090   2090  0.032631
2091   2091  0.411071
2092   2092  0.003392
2093   2093  0.316880
2094   2094  0.175714
2095   2095  0.539711
2096   2096  0.018169
2097   2097  0.230172
2098   2098  0.191655
2099   2099  0.001321
2100   2100  0.676828
2101   2101  0.002500
2102   2102  0.046743
2103   2103  0.571291
2104   2104  0.342225
2105   2105  0.018790
2106   2106  0.057894
2107   2107  0.001694
2108   2108  0.560103
2109   2109  0.001530

[2110 rows x 2 columns]

In [35]:
from sklearn import metrics

In [36]:
y_predict

array([[0.50644251, 0.49355749],
       [0.67532773, 0.32467227],
       [0.99687348, 0.00312652],
       ...,
       [0.99830566, 0.00169434],
       [0.4398968 , 0.5601032 ],
       [0.99847023, 0.00152977]])