In [1]:
import pandas as pd

In [3]:
s=pd.Series([1,2,3,4,"hi"])

In [7]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
print(df.describe())

                X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000

             temp          RH        wind        rain         area
count  517.000000  517.000000  517.000000  517.000000   517.000000
mean    18.889168   44.288201    4.017602    0.021663    12.847292
std      5.806625   16.317469    1.791653    0.295959    63.655818
min      2.200000   15.000000    0.400000    0.000000     0.000000
25%     15.500000   33.000000    2.700000    0.000000     0.000000
50%     19.300000   42.000000    4.000000    0.000000     0.520000
75%     22.800000   53.000000    4.900000    0.000000     6.570000
max     33.300000  100.000000    9.400000    6.400000  1090.840000

In [16]:
df.columns

(517, 13)

In [14]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
# df_2 = #Type your code here
# print(df_2.head())
df.sort_values(['month','day'],ascending=True)
# df

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain    area
241  4  4   apr  fri  83.0   23.3   85.3   2.3  16.7  20   3.1   0.0    0.00
442  6  5   apr  mon  87.9   24.9   41.6   3.7  10.9  64   3.1   0.0    3.35
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0    0.00
239  7  5   apr  sun  81.9    3.0    7.9   3.5  13.4  75   1.8   0.0    0.00
469  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4   0.0   61.13
470  5  4   apr  sun  91.0   14.6   25.6  12.3  17.6  27   5.8   0.0    0.00
176  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0    4.61
196  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0   10.93
240  6  3   apr  wed  88.0   17.2   43.5   3.8  15.2  51   2.7   0.0    0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0    0.00
78   1  2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7   0.0    0.00
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0    0.61
184  8  6   aug  fri  93.9  135.7  586.7  15.1  20.8  34   4.9   0.0    6.96
195  2  5   aug  fri  93.9  135.7  586.7  15.1  23.5  36   5.4   0.0   10.02
261  3  4   aug  fri  91.6  112.4  573.0   8.9  11.2  84   7.6   0.0    3.30
262  2  4   aug  fri  91.6  112.4  573.0   8.9  21.4  42   3.1   0.0    4.25
263  6  3   aug  fri  91.1  141.1  629.1   7.1  19.3  39   3.6   0.0    1.56
264  4  4   aug  fri  94.3  167.6  684.4  13.0  21.8  53   3.1   0.0    6.54
388  6  4   aug  fri  94.8  227.0  706.7  12.0  23.3  34   3.1   0.0   28.74
389  7  4   aug  fri  94.8  227.0  706.7  12.0  23.3  34   3.1   0.0    0.00
402  9  9   aug  fri  94.8  227.0  706.7  12.0  25.0  36   4.0   0.0    0.00
434  1  4   aug  fri  90.6  269.8  811.2   5.5  22.2  45   3.6   0.0    0.00
451  1  4   aug  fri  90.5  196.8  649.9  16.3  11.8  88   4.9   0.0    9.71
492  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0    0.00
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0   43.32
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0    0.00
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0    0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0    0.00
509  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4    2.17
510  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0    0.43
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...     ...
56   4  3   sep  tue  90.3   80.7  730.2   6.3  17.8  63   4.9   0.0    0.00
123  3  4   sep  tue  84.4   73.4  671.9   3.2  17.9  45   3.1   0.0    0.00
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0    0.43
147  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0    0.96
185  2  5   sep  tue  91.0  129.5  692.6   7.0  17.6  46   3.1   0.0    7.04
198  3  4   sep  tue  91.0  129.5  692.6   7.0  13.9  59   6.3   0.0   11.24
200  1  5   sep  tue  91.0  129.5  692.6   7.0  21.6  33   2.2   0.0   11.53
207  7  5   sep  tue  91.0  129.5  692.6   7.0  20.7  37   2.2   0.0   17.20
232  6  4   sep  tue  91.0  129.5  692.6   7.0  18.7  43   2.7   0.0  103.39
233  9  4   sep  tue  84.4   73.4  671.9   3.2  24.3  36   3.1   0.0  105.66
237  1  2   sep  tue  91.0  129.5  692.6   7.0  18.8  40   2.2   0.0  212.88
363  4  3   sep  tue  91.9  111.7  770.3   6.5  15.9  53   2.2   0.0    2.93
364  6  5   sep  tue  91.9  111.7  770.3   6.5  21.1  35   2.7   0.0    5.65
365  6  5   sep  tue  91.9  111.7  770.3   6.5  19.6  45   3.1   0.0   20.03
366  4  5   sep  tue  91.1  132.3  812.1  12.5  15.9  38   5.4   0.0    1.75
367  4  5   sep  tue  91.1  132.3  812.1  12.5  16.4  27   3.6   0.0    0.00
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0    0.00
44   4  4   sep  wed  90.1   82.9  735.7   6.2  12.9  74   4.9   0.0    0.00
45   5  6   sep  wed  94.3   85.1  692.3  15.9  25.9  24   4.0   0.0    0.00
170  5  4   sep  wed  92.9  133.3  699.6   9.2  21.9  35   1.8   0.0    2.57
178  2  5   sep  wed  90.1   82.9  735.7   6.2  18.3  45   2.2   0.0    4.88
193  4  5   sep  wed  92.9  133.3  699.6   9.2  24.3  25   4.0   0.0    9.41
218  4  5   sep  wed  92.9  133.3  699.6   9.2  19.4  19   1.3   0.0   31.72
224  7  4   sep  wed  90.1   82.9  735.7   6.2  15.4  57   4.5   0.0   37.71
230  4  4   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   88.49
313  6  5   sep  wed  92.6  115.4  777.1   8.8  24.3  27   4.9   0.0    0.00
314  4  4   sep  wed  92.6  115.4  777.1   8.8  19.7  41   1.8   0.0    1.58
315  3  4   sep  wed  91.2  134.7  817.5   7.2  18.5  30   2.7   0.0    0.00
404  2  4   sep  wed  87.9   84.8  725.1   3.7  21.8  34   2.2   0.0    6.04
448  7  4   sep  wed  89.7  284.9  844.0  10.1  10.5  77   4.0   0.0    0.00

[517 rows x 13 columns]

In [1]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df[['month', 'day', 'temp', 'area']]

    month  day  temp   area
0     mar  fri   8.2   0.00
1     oct  tue  18.0   0.00
2     oct  sat  14.6   0.00
3     mar  fri   8.3   0.00
4     mar  sun  11.4   0.00
5     aug  sun  22.2   0.00
6     aug  mon  24.1   0.00
7     aug  mon   8.0   0.00
8     sep  tue  13.1   0.00
9     sep  sat  22.8   0.00
10    sep  sat  17.8   0.00
11    sep  sat  19.3   0.00
12    aug  fri  17.0   0.00
13    sep  mon  21.3   0.00
14    sep  wed  26.4   0.00
15    sep  fri  22.9   0.00
16    mar  sat  15.1   0.00
17    oct  mon  16.7   0.00
18    mar  wed  15.9   0.00
19    apr  sat   9.3   0.00
20    sep  tue  18.3   0.00
21    sep  mon  19.1   0.00
22    jun  sun  21.0   0.00
23    aug  sat  19.5   0.00
24    aug  sat  23.7   0.00
25    aug  sun  16.3   0.00
26    sep  fri  19.0   0.00
27    sep  mon  19.4   0.00
28    sep  sat  30.2   0.00
29    sep  sun  22.8   0.00
..    ...  ...   ...    ...
487   aug  tue  26.4  16.40
488   aug  tue  19.4  46.70
489   aug  wed  20.6   0.00
490   aug  wed  28.7   0.00
491   aug  thu  32.4   0.00
492   aug  fri  32.4   0.00
493   aug  fri  27.5  43.32
494   aug  sat  30.8   8.59
495   aug  mon  23.9   0.00
496   aug  mon  32.6   2.77
497   aug  tue  32.3  14.68
498   aug  tue  33.3  40.54
499   aug  tue  27.3  10.82
500   aug  tue  21.6   0.00
501   aug  tue  21.6   0.00
502   aug  tue  20.7   0.00
503   aug  wed  29.2   1.95
504   aug  wed  28.9  49.59
505   aug  thu  26.7   5.80
506   aug  fri  18.5   0.00
507   aug  fri  25.9   0.00
508   aug  fri  25.9   0.00
509   aug  fri  21.1   2.17
510   aug  fri  18.2   0.43
511   aug  sun  27.8   0.00
512   aug  sun  27.8   6.44
513   aug  sun  21.9  54.29
514   aug  sun  21.2  11.16
515   aug  sat  25.6   0.00
516   nov  tue  11.8   0.00

[517 rows x 4 columns]

In [2]:
df.loc[0::2]

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
10   7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
16   5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
18   6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
20   6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
22   7  4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
24   7  4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
26   7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
28   6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
30   6  3   sep  fri  94.3   85.1  692.3  15.9  25.4  24   3.6   0.0   0.00
32   6  3   sep  fri  88.6   69.7  706.8   5.8  20.6  37   1.8   0.0   0.00
34   6  3   sep  mon  91.8   78.5  724.3   9.2  21.2  32   2.7   0.0   0.00
36   6  3   oct  tue  90.6   35.4  669.1   6.7  21.7  24   4.5   0.0   0.00
38   7  3   oct  sat  90.6   43.7  686.9   6.7  17.8  27   4.0   0.0   0.00
40   4  4   jul  tue  79.5   60.6  366.7   1.5  23.3  37   3.1   0.0   0.00
42   4  4   aug  tue  94.8  108.3  647.1  17.0  16.6  54   5.4   0.0   0.00
44   4  4   sep  wed  90.1   82.9  735.7   6.2  12.9  74   4.9   0.0   0.00
46   5  6   sep  mon  90.9  126.5  686.5   7.0  14.7  70   3.6   0.0   0.00
48   4  4   mar  mon  87.2   23.9   64.7   4.1  11.8  35   1.8   0.0   0.00
50   4  4   sep  thu  92.9  137.0  706.4   9.2  20.8  17   1.3   0.0   0.00
52   4  3   aug  wed  92.1  111.2  654.1   9.6  20.4  42   4.9   0.0   0.00
54   4  3   aug  thu  91.7  114.3  661.3   6.3  17.6  45   3.6   0.0   0.00
56   4  3   sep  tue  90.3   80.7  730.2   6.3  17.8  63   4.9   0.0   0.00
58   2  2   feb  mon  84.0    9.3   34.0   2.1  13.9  40   5.4   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
458  8  6   aug  sat  93.7  231.1  715.1   8.4  18.9  64   4.9   0.0   3.32
460  2  5   aug  sat  93.7  231.1  715.1   8.4  18.9  64   4.9   0.0   0.00
462  1  4   sep  sun  91.0  276.3  825.1   7.1  14.5  76   7.6   0.0   3.71
464  6  4   feb  tue  75.1    4.4   16.2   1.9   5.1  77   5.4   0.0   2.14
466  6  5   mar  mon  87.2   15.1   36.9   7.1  10.2  45   5.8   0.0   3.18
468  6  5   mar  thu  91.3   20.6   43.5   8.5  13.3  27   3.6   0.0   6.61
470  5  4   apr  sun  91.0   14.6   25.6  12.3  17.6  27   5.8   0.0   0.00
472  8  3   jun  mon  88.2   96.2  229.0   4.7  14.3  79   4.0   0.0   1.94
474  4  3   jun  thu  93.0  103.8  316.7  10.8  26.4  35   2.7   0.0  10.08
476  4  3   jul  thu  93.5   85.3  395.0   9.9  27.2  28   1.3   0.0   1.76
478  7  4   jul  sun  93.7  101.3  423.4  14.7  18.2  82   4.5   0.0   2.21
480  9  9   jul  thu  93.2  114.4  560.0   9.5  30.2  25   4.5   0.0   2.75
482  3  4   aug  sun  94.9  130.3  587.1  14.1  23.4  40   5.8   0.0   1.29
484  2  5   aug  sun  94.9  130.3  587.1  14.1  33.1  25   4.0   0.0  26.43
486  5  4   aug  tue  95.1  141.3  605.8  17.7  24.1  43   6.3   0.0   2.00
488  4  4   aug  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
490  4  4   aug  wed  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
492  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
494  6  6   aug  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
496  4  5   aug  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
498  6  5   aug  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
500  8  6   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4   aug  tue  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
510  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[259 rows x 13 columns]

In [34]:
# x=df.set_index("X",inplace=True)
# x
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')


# df2=df.set_index("X",inplace=True)
type(df.set_index("X",inplace=True))

NoneType

In [66]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 =df.iloc[2:21,] #Type your code for indexing using iloc

In [1]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df.loc[(df.area>0 ) & (df.wind >1)]

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain    area
138  9  9   jul  tue  85.8   48.3  313.4   3.9  18.0  42   2.7   0.0    0.36
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0    0.43
140  2  5   sep  mon  90.9  126.5  686.5   7.0  21.9  39   1.8   0.0    0.47
141  1  2   aug  wed  95.5   99.9  513.3  13.2  23.3  31   4.5   0.0    0.55
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0    0.61
143  1  2   jul  sat  90.0   51.3  296.3   8.7  16.6  53   5.4   0.0    0.71
144  2  5   aug  wed  95.5   99.9  513.3  13.2  23.8  32   5.4   0.0    0.77
145  6  5   aug  thu  95.2  131.7  578.8  10.4  27.4  22   4.0   0.0    0.90
146  5  4   mar  mon  90.1   39.7   86.6   6.2  13.2  40   5.4   0.0    0.95
147  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0    0.96
148  2  2   aug  tue  94.8  108.3  647.1  17.0  17.4  43   6.7   0.0    1.07
149  8  6   sep  thu  93.7   80.9  685.2  17.9  23.7  25   4.5   0.0    1.12
150  6  5   jun  fri  92.5   56.4  433.3   7.1  23.2  39   5.4   0.0    1.19
151  9  9   jul  sun  90.1   68.6  355.2   7.2  24.8  29   2.2   0.0    1.36
152  3  4   jul  sat  90.1   51.2  424.1   6.2  24.6  43   1.8   0.0    1.43
153  5  4   sep  fri  94.3   85.1  692.3  15.9  20.1  47   4.9   0.0    1.46
154  1  5   sep  sat  93.4  145.4  721.4   8.1  29.6  27   2.7   0.0    1.46
155  7  4   aug  sun  94.8  108.3  647.1  17.0  16.4  47   1.3   0.0    1.56
156  2  4   sep  sat  93.4  145.4  721.4   8.1  28.6  27   2.2   0.0    1.61
157  2  2   aug  wed  92.1  111.2  654.1   9.6  18.4  45   3.6   0.0    1.63
158  2  4   aug  wed  92.1  111.2  654.1   9.6  20.5  35   4.0   0.0    1.64
159  7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0    1.69
160  7  4   mar  mon  90.1   39.7   86.6   6.2  16.1  29   3.1   0.0    1.75
161  6  4   aug  thu  95.2  131.7  578.8  10.4  20.3  41   4.0   0.0    1.90
162  6  3   mar  sat  90.6   50.1  100.4   7.8  15.2  31   8.5   0.0    1.94
163  8  6   sep  sat  92.5  121.1  674.4   8.6  17.8  56   1.8   0.0    1.95
164  8  5   sep  sun  89.7   90.0  704.4   4.8  17.8  67   2.2   0.0    2.01
165  6  5   mar  thu  84.9   18.2   55.0   3.0   5.3  70   4.5   0.0    2.14
167  6  5   aug  wed  96.0  127.1  570.5  16.5  23.4  33   4.5   0.0    2.51
168  6  5   mar  fri  91.2   48.3   97.8  12.5  14.6  26   9.4   0.0    2.53
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...     ...
471  4  3   may  fri  89.6   25.4   73.7   5.7  18.0  40   4.0   0.0   38.48
472  8  3   jun  mon  88.2   96.2  229.0   4.7  14.3  79   4.0   0.0    1.94
473  9  4   jun  sat  90.5   61.1  252.6   9.4  24.5  50   3.1   0.0   70.32
474  4  3   jun  thu  93.0  103.8  316.7  10.8  26.4  35   2.7   0.0   10.08
475  2  5   jun  thu  93.7  121.7  350.2  18.0  22.7  40   9.4   0.0    3.19
476  4  3   jul  thu  93.5   85.3  395.0   9.9  27.2  28   1.3   0.0    1.76
477  4  3   jul  sun  93.7  101.3  423.4  14.7  26.1  45   4.0   0.0    7.36
478  7  4   jul  sun  93.7  101.3  423.4  14.7  18.2  82   4.5   0.0    2.21
479  7  4   jul  mon  89.2  103.9  431.6   6.4  22.6  57   4.9   0.0  278.53
480  9  9   jul  thu  93.2  114.4  560.0   9.5  30.2  25   4.5   0.0    2.75
482  3  4   aug  sun  94.9  130.3  587.1  14.1  23.4  40   5.8   0.0    1.29
484  2  5   aug  sun  94.9  130.3  587.1  14.1  33.1  25   4.0   0.0   26.43
485  2  4   aug  mon  95.0  135.5  596.3  21.3  30.6  28   3.6   0.0    2.07
486  5  4   aug  tue  95.1  141.3  605.8  17.7  24.1  43   6.3   0.0    2.00
487  5  4   aug  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0   16.40
488  4  4   aug  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0   46.70
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0   43.32
494  6  6   aug  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0    8.59
496  4  5   aug  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0    2.77
497  3  4   aug  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0   14.68
498  6  5   aug  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0   40.54
499  7  5   aug  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4   10.82
503  2  4   aug  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0    1.95
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0   49.59
505  1  2   aug  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0    5.80
509  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4    2.17
510  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0    0.43
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0    6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0   54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0   11.16

[264 rows x 13 columns]

In [7]:
import pandas as pd
df_1 = pd.read_csv('https://query.data.world/s/vv3snq28bp0TJq2ggCdxGOghEQKPZo')
df_2 = pd.read_csv('https://query.data.world/s/9wVKjNT0yiRc3YbVJaiI8a6HGl2d74')
# df_3 = #Type your code here.
# print(df_3.head(20))
pd.merge(df_1,df_2,on="unique_id",how='inner')
# df_2

,name,address,city,cuisine,unique_id,name_2,address_2,city_2,cuisine_2
0,arnie morton's of chicago,"""435 s. la cienega blvd.""","""los angeles""","""steakhouses""",'0',arnie morton's of chicago,"""435 s. la cienega blv.""","""los angeles""","""american"""
1,art's deli,"""12224 ventura blvd.""","""studio city""","""delis""",'1',art's delicatessen,"""12224 ventura blvd.""","""studio city""","""american"""
2,bel-air hotel,"""701 stone canyon rd.""","""bel air""","""californian""",'2',hotel bel-air,"""701 stone canyon rd.""","""bel air""","""californian"""
3,cafe bizou,"""14016 ventura blvd.""","""sherman oaks""","""french bistro""",'3',cafe bizou,"""14016 ventura blvd.""","""sherman oaks""","""french"""
4,campanile,"""624 s. la brea ave.""","""los angeles""","""californian""",'4',campanile,"""624 s. la brea ave.""","""los angeles""","""american"""
5,chinois on main,"""2709 main st.""","""santa monica""","""pacific new wave""",'5',chinois on main,"""2709 main st.""","""santa monica""","""french"""
6,citrus,"""6703 melrose ave.""","""los angeles""","""californian""",'6',citrus,"""6703 melrose ave.""","""los angeles""","""californian"""
7,fenix at the argyle,"""8358 sunset blvd.""","""w. hollywood""","""french (new)""",'7',fenix,"""8358 sunset blvd. west""","""hollywood""","""american"""
8,granita,"""23725 w. malibu rd.""","""malibu""","""californian""",'8',granita,"""23725 w. malibu rd.""","""malibu""","""californian"""
9,grill the,"""9560 dayton way""","""beverly hills""","""american (traditional)""",'9',grill on the alley,"""9560 dayton way""","""los angeles""","""american"""
10,katsu,"""1972 hillhurst ave.""","""los feliz""","""japanese""",'10',restaurant katsu,"""1972 n. hillhurst ave.""","""los angeles""","""asian"""
11,l'orangerie,"""903 n. la cienega blvd.""","""w. hollywood""","""french (classic)""",'11',l'orangerie,"""903 n. la cienega blvd.""","""los angeles""","""french"""
12,le chardonnay (los angeles),"""8284 melrose ave.""","""los angeles""","""french bistro""",'12',le chardonnay,"""8284 melrose ave.""","""los angeles""","""french"""
13,locanda veneta,"""8638 w. third st.""","""los angeles""","""italian""",'13',locanda veneta,"""3rd st.""","""los angeles""","""italian"""
14,matsuhisa,"""129 n. la cienega blvd.""","""beverly hills""","""seafood""",'14',matsuhisa,"""129 n. la cienega blvd.""","""beverly hills""","""asian"""
15,palm the (los angeles),"""9001 santa monica blvd.""","""w. hollywood""","""steakhouses""",'15',the palm,"""9001 santa monica blvd.""","""los angeles""","""american"""
16,patina,"""5955 melrose ave.""","""los angeles""","""californian""",'16',patina,"""5955 melrose ave.""","""los angeles""","""californian"""
17,philippe the original,"""1001 n. alameda st.""","""chinatown""","""cafeterias""",'17',philippe's the original,"""1001 n. alameda st.""","""los angeles""","""american"""
18,pinot bistro,"""12969 ventura blvd.""","""studio city""","""french bistro""",'18',pinot bistro,"""12969 ventura blvd.""","""los angeles""","""french"""
19,rex il ristorante,"""617 s. olive st.""","""los angeles""","""nuova cucina italian""",'19',rex il ristorante,"""617 s. olive st.""","""los angeles""","""italian"""
20,spago (los angeles),"""8795 sunset blvd.""","""w. hollywood""","""californian""",'20',spago,"""1114 horn ave.""","""los angeles""","""californian"""
21,valentino,"""3115 pico blvd.""","""santa monica""","""italian""",'21',valentino,"""3115 pico blvd.""","""santa monica""","""italian"""
22,yujean kang's,"""67 n. raymond ave.""","""pasadena""","""chinese""",'22',yujean kang's gourmet chinese cuisine,"""67 n. raymond ave.""","""los angeles""","""asian"""
23,21 club,"""21 w. 52nd st.""","""new york city""","""american (new)""",'23',21 club,"""21 w. 52nd st.""","""new york""","""american"""
24,aquavit,"""13 w. 54th st.""","""new york city""","""scandinavian""",'24',aquavit,"""13 w. 54th st.""","""new york""","""continental"""
25,aureole,"""34 e. 61st st.""","""new york city""","""american (new)""",'25',aureole,"""34 e. 61st st.""","""new york""","""american"""
26,cafe lalo,"""201 w. 83rd st.""","""new york city""","""coffeehouses""",'26',cafe lalo,"""201 w. 83rd st.""","""new york""","""coffee bar"""
27,cafe des artistes,"""1 w. 67th st.""","""new york city""","""french (classic)""",'27',cafe des artistes,"""1 w. 67th st.""","""new york""","""continental"""
28,carmine's,"""2450 broadway""","""new york city""","""italian""",'28',carmine's,"""2450 broadway between 90th and 91st sts.""","""new york""","""italian"""
29,carnegie deli,"""854 seventh ave.""","""new york city""","""delis""",'29',carnegie deli,"""854 7th ave. between 54th and 55th sts.""","""new york""","""delicatessen"""
...,...,...,...,...,...,...,...,...,...
82,hedgerose heights inn the,"""490 e. paces ferry rd. ne""","""atlanta""","""continental""",'82',hedgerose heights inn,"""490 e. paces ferry rd.""","""atlanta""","""international"""
83,heera of india,"""595 piedmont ave.""","""atlanta""","""indian""",'83',heera of india,"""595 piedmont ave. rio shopping mall""","""atlanta""","""asian"""
84,indigo coastal grill,"""1397 n. highland ave.""","""atlanta""","""eclectic""",'84',indigo coastal grill,"""1397 n. highland ave.""","""atlanta""","""caribbean"""
85,la grotta,"""2637 peachtree rd. ne""","""atlanta""","""italian""",'85',la grotta,"""2637 peachtree rd. peachtree house condomin...","""atlanta""","""italian"""
86,mary mac's tea room,"""224 ponce de leon ave.""","""atlanta""","""southern/soul""",'86',mary mac's tea room,"""224 ponce de leon ave.""","""atlanta""","""southern"""
87,nikolai's roof,"""255 courtland st.""","""atlanta""","""continental""",'87',nikolai's roof,"""255 courtland st. at harris st.""","""atlanta""","""continental"""
88,pano's & paul's,"""1232 w. paces ferry rd.""","""atlanta""","""american (new)""",'88',pano's and paul's,"""1232 w. paces ferry rd.""","""atlanta""","""international"""
89,ritz-carlton cafe (buckhead),"""3434 peachtree rd. ne""","""atlanta""","""american (new)""",'89',cafe ritz-carlton buckhead,"""3434 peachtree rd.""","""atlanta""","""ext 6108 international"""
90,ritz-carlton dining room (buckhead),"""3434 peachtree rd. ne""","""atlanta""","""american (new)""",'90',dining room ritz-carlton buckhead,"""3434 peachtree rd.""","""atlanta""","""international"""
91,ritz-carlton restaurant,"""181 peachtree st.""","""atlanta""","""french (classic)""",'91',restaurant ritz-carlton atlanta,"""181 peachtree st.""","""atlanta""","""continental"""
92,toulouse,"""293-b peachtree rd.""","""atlanta""","""french (new)""",'92',toulouse,"""b peachtree rd.""","""atlanta""","""french"""
93,veni vidi vici,"""41 14th st.""","""atlanta""","""italian""",'93',veni vidi vici,"""41 14th st.""","""atlanta""","""italian"""
94,alain rondelli,"""126 clement st.""","""san francisco""","""french (new)""",'94',alain rondelli,"""126 clement st.""","""san francisco""","""french"""
95,aqua,"""252 california st.""","""san francisco""","""american (new)""",'95',aqua,"""252 california st.""","""san francisco""","""seafood"""
96,boulevard,"""1 mission st.""","""san francisco""","""american (new)""",'96',boulevard,"""1 mission st.""","""san francisco""","""american"""
97,cafe claude,"""7 claude ln.""","""san francisco""","""french bistro""",'97',cafe claude,"""7 claude la.""","""san francisco""","""french"""
98,campton place,"""340 stockton st.""","""san francisco""","""american (new)""",'98',campton place,"""340 stockton st.""","""san francisco""","""american"""
99,chez michel,"""804 north point st.""","""san francisco""","""californian""",'99',chez michel,"""804 northpoint""","""san francisco""","""french"""
100,fleur de lys,"""777 sutter st.""","""san francisco""","""french (new)""",'100',fleur de lys,"""777 sutter st.""","""san francisco""","""french"""
101,fringale,"""570 fourth st.""","""san francisco""","""french bistro""",'101',fringale,"""570 4th st.""","""san francisco""","""french"""
102,hawthorne lane,"""22 hawthorne st.""","""san francisco""","""californian""",'102',hawthorne lane,"""22 hawthorne st.""","""san francisco""","""american"""
103,khan toke thai house,"""5937 geary blvd.""","""san francisco""","""thai""",'103',khan toke thai house,"""5937 geary blvd.""","""san francisco""","""asian"""
104,la folie,"""2316 polk st.""","""san francisco""","""french (new)""",'104',la folie,"""2316 polk st.""","""san francisco""","""french"""
105,lulu restaurant-bis-cafe,"""816 folsom st.""","""san francisco""","""mediterranean""",'105',lulu,"""816 folsom st.""","""san francisco""","""mediterranean"""
106,masa's,"""648 bush st.""","""san francisco""","""french (new)""",'106',masa's,"""648 bush st.""","""san francisco""","""french"""
107,mifune,"""1737 post st.""","""san francisco""","""japanese""",'107',mifune japan center kintetsu building,"""1737 post st.""","""san francisco""","""asian"""
108,plumpjack cafe,"""3127 fillmore st.""","""san francisco""","""american (new)""",'108',plumpjack cafe,"""3201 fillmore st.""","""san francisco""","""mediterranean"""
109,postrio,"""545 post st.""","""san francisco""","""californian""",'109',postrio,"""545 post st.""","""san francisco""","""american"""
110,ritz-carlton dining room (san francisco),"""600 stockton st.""","""san francisco""","""french (new)""",'110',ritz-carlton restaurant and dining room,"""600 stockton st.""","""san francisco""","""american"""
111,rose pistola,"""532 columbus ave.""","""san francisco""","""italian""",'111',rose pistola,"""532 columbus ave.""","""san francisco""","""italian"""

In [13]:
import pandas as pd
df_1 = pd.read_csv('https://query.data.world/s/vv3snq28bp0TJq2ggCdxGOghEQKPZo')
df_2 = pd.read_csv('https://query.data.world/s/9wVKjNT0yiRc3YbVJaiI8a6HGl2d74')
# df_3 =#Type your code here.
pd.concat([df_1,df_2],axis=0)

,address,address_2,city,city_2,cuisine,cuisine_2,name,name_2,unique_id
0,"""435 s. la cienega blvd.""",NaN,"""los angeles""",NaN,"""steakhouses""",NaN,arnie morton's of chicago,NaN,'0'
1,"""12224 ventura blvd.""",NaN,"""studio city""",NaN,"""delis""",NaN,art's deli,NaN,'1'
2,"""701 stone canyon rd.""",NaN,"""bel air""",NaN,"""californian""",NaN,bel-air hotel,NaN,'2'
3,"""14016 ventura blvd.""",NaN,"""sherman oaks""",NaN,"""french bistro""",NaN,cafe bizou,NaN,'3'
4,"""624 s. la brea ave.""",NaN,"""los angeles""",NaN,"""californian""",NaN,campanile,NaN,'4'
5,"""2709 main st.""",NaN,"""santa monica""",NaN,"""pacific new wave""",NaN,chinois on main,NaN,'5'
6,"""6703 melrose ave.""",NaN,"""los angeles""",NaN,"""californian""",NaN,citrus,NaN,'6'
7,"""8358 sunset blvd.""",NaN,"""w. hollywood""",NaN,"""french (new)""",NaN,fenix at the argyle,NaN,'7'
8,"""23725 w. malibu rd.""",NaN,"""malibu""",NaN,"""californian""",NaN,granita,NaN,'8'
9,"""9560 dayton way""",NaN,"""beverly hills""",NaN,"""american (traditional)""",NaN,grill the,NaN,'9'
10,"""1972 hillhurst ave.""",NaN,"""los feliz""",NaN,"""japanese""",NaN,katsu,NaN,'10'
11,"""903 n. la cienega blvd.""",NaN,"""w. hollywood""",NaN,"""french (classic)""",NaN,l'orangerie,NaN,'11'
12,"""8284 melrose ave.""",NaN,"""los angeles""",NaN,"""french bistro""",NaN,le chardonnay (los angeles),NaN,'12'
13,"""8638 w. third st.""",NaN,"""los angeles""",NaN,"""italian""",NaN,locanda veneta,NaN,'13'
14,"""129 n. la cienega blvd.""",NaN,"""beverly hills""",NaN,"""seafood""",NaN,matsuhisa,NaN,'14'
15,"""9001 santa monica blvd.""",NaN,"""w. hollywood""",NaN,"""steakhouses""",NaN,palm the (los angeles),NaN,'15'
16,"""5955 melrose ave.""",NaN,"""los angeles""",NaN,"""californian""",NaN,patina,NaN,'16'
17,"""1001 n. alameda st.""",NaN,"""chinatown""",NaN,"""cafeterias""",NaN,philippe the original,NaN,'17'
18,"""12969 ventura blvd.""",NaN,"""studio city""",NaN,"""french bistro""",NaN,pinot bistro,NaN,'18'
19,"""617 s. olive st.""",NaN,"""los angeles""",NaN,"""nuova cucina italian""",NaN,rex il ristorante,NaN,'19'
20,"""8795 sunset blvd.""",NaN,"""w. hollywood""",NaN,"""californian""",NaN,spago (los angeles),NaN,'20'
21,"""3115 pico blvd.""",NaN,"""santa monica""",NaN,"""italian""",NaN,valentino,NaN,'21'
22,"""67 n. raymond ave.""",NaN,"""pasadena""",NaN,"""chinese""",NaN,yujean kang's,NaN,'22'
23,"""21 w. 52nd st.""",NaN,"""new york city""",NaN,"""american (new)""",NaN,21 club,NaN,'23'
24,"""13 w. 54th st.""",NaN,"""new york city""",NaN,"""scandinavian""",NaN,aquavit,NaN,'24'
25,"""34 e. 61st st.""",NaN,"""new york city""",NaN,"""american (new)""",NaN,aureole,NaN,'25'
26,"""201 w. 83rd st.""",NaN,"""new york city""",NaN,"""coffeehouses""",NaN,cafe lalo,NaN,'26'
27,"""1 w. 67th st.""",NaN,"""new york city""",NaN,"""french (classic)""",NaN,cafe des artistes,NaN,'27'
28,"""2450 broadway""",NaN,"""new york city""",NaN,"""italian""",NaN,carmine's,NaN,'28'
29,"""854 seventh ave.""",NaN,"""new york city""",NaN,"""delis""",NaN,carnegie deli,NaN,'29'
...,...,...,...,...,...,...,...,...,...
722,NaN,"""423 columbus ave.""",NaN,"""san francisco""",NaN,"""continental""",NaN,caffe greco,'723'
723,NaN,"""240 columbus ave.""",NaN,"""san francisco""",NaN,"""mexican""",NaN,campo santo,'724'
724,NaN,"""1805 haight st.""",NaN,"""san francisco""",NaN,"""caribbean""",NaN,cha cha cha's,'725'
725,NaN,"""2217 union st.""",NaN,"""san francisco""",NaN,"""american""",NaN,doidge's,'726'
726,NaN,"""522 jones st.""",NaN,"""san francisco""",NaN,"""diners""",NaN,dottie's true blue cafe,'727'
727,NaN,"""3221 mission st.""",NaN,"""san francisco""",NaN,"""thai""",NaN,dusit thai,'728'
728,NaN,"""1283 ninth ave.""",NaN,"""san francisco""",NaN,"""japanese""",NaN,ebisu,'729'
729,NaN,"""1550 california st.""",NaN,"""san francisco""",NaN,"""vietnamese""",NaN,emerald garden restaurant,'730'
730,NaN,"""1500 church st.""",NaN,"""san francisco""",NaN,"""chinese""",NaN,eric's chinese restaurant,'731'
731,NaN,"""1582 folsom st.""",NaN,"""san francisco""",NaN,"""hamburgers""",NaN,hamburger mary's,'732'
732,NaN,"""333 bush st.""",NaN,"""san francisco""",NaN,"""californian""",NaN,kelly's on trinity,'733'
733,NaN,"""515 valencia st.""",NaN,"""san francisco""",NaN,"""mexican""",NaN,la cumbre,'734'
734,NaN,"""288 noe st.""",NaN,"""san francisco""",NaN,"""mediterranean""",NaN,la mediterranee,'735'
735,NaN,"""2889 mission st.""",NaN,"""san francisco""",NaN,"""mexican""",NaN,la taqueria,'736'
736,NaN,"""2209 polk st.""",NaN,"""san francisco""",NaN,"""italian""",NaN,mario's bohemian cigar store cafe,'737'
737,NaN,"""2225 irving st.""",NaN,"""san francisco""",NaN,"""thai""",NaN,marnee thai,'738'
738,NaN,"""3355 geary st.""",NaN,"""san francisco""",NaN,"""hamburgers""",NaN,mel's drive-in,'739'
739,NaN,"""1322 grant st.""",NaN,"""san francisco""",NaN,"""hamburgers""",NaN,mo's burgers,'740'
740,NaN,"""631 larkin st.""",NaN,"""san francisco""",NaN,"""cambodian""",NaN,phnom penh cambodian restaurant,'741'
741,NaN,"""2817 24th st.""",NaN,"""san francisco""",NaN,"""mexican""",NaN,roosevelt tamale parlor,'742'
742,NaN,"""300 de haro st.""",NaN,"""san francisco""",NaN,"""american""",NaN,sally's cafe & bakery,'743'
743,NaN,"""1328 18th st.""",NaN,"""san francisco""",NaN,"""thai""",NaN,san francisco bbq,'744'
744,NaN,"""584 valencia st.""",NaN,"""san francisco""",NaN,"""vietnamese""",NaN,slanted door,'745'
745,NaN,"""1517 polk st.""",NaN,"""san francisco""",NaN,"""seafood""",NaN,swan oyster depot,'746'
746,NaN,"""400 waller st.""",NaN,"""san francisco""",NaN,"""thai""",NaN,thep phanom,'747'
747,NaN,"""3108 16th st.""",NaN,"""san francisco""",NaN,"""french""",NaN,ti couz,'748'
748,NaN,"""1870 fillmore st.""",NaN,"""san francisco""",NaN,"""american""",NaN,trio cafe,'749'
749,NaN,"""8 sixth st.""",NaN,"""san francisco""",NaN,"""vietnamese""",NaN,tu lan,'750'
750,NaN,"""201 ivy st.""",NaN,"""san francisco""",NaN,"""pizza""",NaN,vicolo pizzeria,'751'
751,NaN,"""2141 polk st.""",NaN,"""san francisco""",NaN,"""mexican""",NaN,wa-ha-ka oaxaca mexican grill,'752'

In [30]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
#Type your groupby command here

df1=df.groupby(["month","day"])

df_1 = df1["rain","wind"].mean() #Type your code to find the mean of columns 'rain' and 'wind'
# print(df_1.head(20))

df_1["test"]=df_1.wind.apply(lambda c: "hi")
df_1

               rain      wind test
month day
apr   fri  0.000000  3.100000   hi
      mon  0.000000  3.100000   hi
      sat  0.000000  4.500000   hi
      sun  0.000000  5.666667   hi
      thu  0.000000  5.800000   hi
      wed  0.000000  2.700000   hi
aug   fri  0.066667  4.766667   hi
      mon  0.000000  2.873333   hi
      sat  0.000000  4.310345   hi
      sun  0.025000  4.417500   hi
      thu  0.000000  3.503846   hi
      tue  0.300000  4.567857   hi
      wed  0.000000  3.520000   hi
dec   fri  0.000000  4.900000   hi
      mon  0.000000  8.500000   hi
      sun  0.000000  8.500000   hi
      thu  0.000000  4.900000   hi
      tue  0.000000  8.500000   hi
      wed  0.000000  8.000000   hi
feb   fri  0.000000  4.820000   hi
      mon  0.000000  4.500000   hi
      sat  0.000000  2.350000   hi
      sun  0.000000  2.550000   hi
      thu  0.000000  3.100000   hi
      tue  0.000000  5.850000   hi
      wed  0.000000  3.100000   hi
jan   sat  0.000000  3.100000   hi
      sun  0.000000  0.900000   hi
jul   fri  0.000000  4.300000   hi
      mon  0.000000  3.800000   hi
...             ...       ...  ...
      wed  0.066667  6.266667   hi
jun   fri  0.000000  4.800000   hi
      mon  0.000000  4.766667   hi
      sat  0.000000  2.900000   hi
      sun  0.000000  2.450000   hi
      thu  0.000000  6.050000   hi
      wed  0.000000  4.633333   hi
mar   fri  0.018182  5.863636   hi
      mon  0.000000  4.083333   hi
      sat  0.000000  5.010000   hi
      sun  0.000000  4.600000   hi
      thu  0.000000  4.480000   hi
      tue  0.000000  5.380000   hi
      wed  0.000000  5.800000   hi
may   fri  0.000000  4.000000   hi
      sat  0.000000  4.900000   hi
nov   tue  0.000000  4.500000   hi
oct   fri  0.000000  5.400000   hi
      mon  0.000000  4.350000   hi
      sat  0.000000  2.800000   hi
      sun  0.000000  3.000000   hi
      tue  0.000000  2.700000   hi
      wed  0.000000  3.150000   hi
sep   fri  0.000000  3.910526   hi
      mon  0.000000  3.107143   hi
      sat  0.000000  3.460000   hi
      sun  0.000000  3.955556   hi
      thu  0.000000  3.357143   hi
      tue  0.000000  3.431579   hi
      wed  0.000000  3.378571   hi

[64 rows x 3 columns]

In [36]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
# df['XY'] = #Type your code here.
# print(df.head(20))
df["XY"]=df["X"]*df["Y"]
df

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,XY
0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,35
1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,28
2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,28
3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,48
4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,48
5,8,6,aug,sun,92.3,85.3,488.0,14.7,22.2,29,5.4,0.0,0.00,48
6,8,6,aug,mon,92.3,88.9,495.6,8.5,24.1,27,3.1,0.0,0.00,48
7,8,6,aug,mon,91.5,145.4,608.2,10.7,8.0,86,2.2,0.0,0.00,48
8,8,6,sep,tue,91.0,129.5,692.6,7.0,13.1,63,5.4,0.0,0.00,48
9,7,5,sep,sat,92.5,88.0,698.6,7.1,22.8,40,4.0,0.0,0.00,35
10,7,5,sep,sat,92.5,88.0,698.6,7.1,17.8,51,7.2,0.0,0.00,35
11,7,5,sep,sat,92.8,73.2,713.0,22.6,19.3,38,4.0,0.0,0.00,35
12,6,5,aug,fri,63.5,70.8,665.3,0.8,17.0,72,6.7,0.0,0.00,30
13,6,5,sep,mon,90.9,126.5,686.5,7.0,21.3,42,2.2,0.0,0.00,30
14,6,5,sep,wed,92.9,133.3,699.6,9.2,26.4,21,4.5,0.0,0.00,30
15,6,5,sep,fri,93.3,141.2,713.9,13.9,22.9,44,5.4,0.0,0.00,30
16,5,5,mar,sat,91.7,35.8,80.8,7.8,15.1,27,5.4,0.0,0.00,25
17,8,5,oct,mon,84.9,32.8,664.2,3.0,16.7,47,4.9,0.0,0.00,40
18,6,4,mar,wed,89.2,27.9,70.8,6.3,15.9,35,4.0,0.0,0.00,24
19,6,4,apr,sat,86.3,27.4,97.1,5.1,9.3,44,4.5,0.0,0.00,24
20,6,4,sep,tue,91.0,129.5,692.6,7.0,18.3,40,2.7,0.0,0.00,24
21,5,4,sep,mon,91.8,78.5,724.3,9.2,19.1,38,2.7,0.0,0.00,20
22,7,4,jun,sun,94.3,96.3,200.0,56.1,21.0,44,4.5,0.0,0.00,28
23,7,4,aug,sat,90.2,110.9,537.4,6.2,19.5,43,5.8,0.0,0.00,28
24,7,4,aug,sat,93.5,139.4,594.2,20.3,23.7,32,5.8,0.0,0.00,28
25,7,4,aug,sun,91.4,142.4,601.4,10.6,16.3,60,5.4,0.0,0.00,28
26,7,4,sep,fri,92.4,117.9,668.0,12.2,19.0,34,5.8,0.0,0.00,28
27,7,4,sep,mon,90.9,126.5,686.5,7.0,19.4,48,1.3,0.0,0.00,28
28,6,3,sep,sat,93.4,145.4,721.4,8.1,30.2,24,2.7,0.0,0.00,18
29,6,3,sep,sun,93.5,149.3,728.6,8.1,22.8,39,3.6,0.0,0.00,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,5,4,aug,tue,95.1,141.3,605.8,17.7,26.4,34,3.6,0.0,16.40,20
488,4,4,aug,tue,95.1,141.3,605.8,17.7,19.4,71,7.6,0.0,46.70,16
489,4,4,aug,wed,95.1,141.3,605.8,17.7,20.6,58,1.3,0.0,0.00,16
490,4,4,aug,wed,95.1,141.3,605.8,17.7,28.7,33,4.0,0.0,0.00,16
491,4,4,aug,thu,95.8,152.0,624.1,13.8,32.4,21,4.5,0.0,0.00,16
492,1,3,aug,fri,95.9,158.0,633.6,11.3,32.4,27,2.2,0.0,0.00,3
493,1,3,aug,fri,95.9,158.0,633.6,11.3,27.5,29,4.5,0.0,43.32,3
494,6,6,aug,sat,96.0,164.0,643.0,14.0,30.8,30,4.9,0.0,8.59,36
495,6,6,aug,mon,96.2,175.5,661.8,16.8,23.9,42,2.2,0.0,0.00,36
496,4,5,aug,mon,96.2,175.5,661.8,16.8,32.6,26,3.1,0.0,2.77,20
497,3,4,aug,tue,96.1,181.1,671.2,14.3,32.3,27,2.2,0.0,14.68,12
498,6,5,aug,tue,96.1,181.1,671.2,14.3,33.3,26,2.7,0.0,40.54,30
499,7,5,aug,tue,96.1,181.1,671.2,14.3,27.3,63,4.9,6.4,10.82,35
500,8,6,aug,tue,96.1,181.1,671.2,14.3,21.6,65,4.9,0.8,0.00,48
501,7,5,aug,tue,96.1,181.1,671.2,14.3,21.6,65,4.9,0.8,0.00,35
502,4,4,aug,tue,96.1,181.1,671.2,14.3,20.7,69,4.9,0.4,0.00,16
503,2,4,aug,wed,94.5,139.4,689.1,20.0,29.2,30,4.9,0.0,1.95,8
504,4,3,aug,wed,94.5,139.4,689.1,20.0,28.9,29,4.9,0.0,49.59,12
505,1,2,aug,thu,91.0,163.2,744.4,10.1,26.7,35,1.8,0.0,5.80,2
506,1,2,aug,fri,91.0,166.9,752.6,7.1,18.5,73,8.5,0.0,0.00,2
507,2,4,aug,fri,91.0,166.9,752.6,7.1,25.9,41,3.6,0.0,0.00,8
508,1,2,aug,fri,91.0,166.9,752.6,7.1,25.9,41,3.6,0.0,0.00,2
509,5,4,aug,fri,91.0,166.9,752.6,7.1,21.1,71,7.6,1.4,2.17,20
510,6,5,aug,fri,91.0,166.9,752.6,7.1,18.2,62,5.4,0.0,0.43,30
511,8,6,aug,sun,81.6,56.7,665.6,1.9,27.8,35,2.7,0.0,0.00,48
512,4,3,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,12
513,2,4,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,8
514,7,4,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,28
515,1,4,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,4
516,6,3,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,18

In [48]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
# # df_1 = #Type your code here. 
# # print(df_1.head(20))

# df.pivot_table(values=["month","day"],index=["month","day"] ,aggfunc="mean")
# df = pd.DataFrame({"a": [1,2,3,1,2,3], "b":[1,1,1,2,2,2], "c":np.random.rand(6)})
pd.pivot_table(df, index=["month","day"], values= ["rain","wind"], aggfunc=np.mean)

               rain      wind
month day
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000
      mon  0.000000  4.500000
      sat  0.000000  2.350000
      sun  0.000000  2.550000
      thu  0.000000  3.100000
      tue  0.000000  5.850000
      wed  0.000000  3.100000
jan   sat  0.000000  3.100000
      sun  0.000000  0.900000
jul   fri  0.000000  4.300000
      mon  0.000000  3.800000
...             ...       ...
      wed  0.066667  6.266667
jun   fri  0.000000  4.800000
      mon  0.000000  4.766667
      sat  0.000000  2.900000
      sun  0.000000  2.450000
      thu  0.000000  6.050000
      wed  0.000000  4.633333
mar   fri  0.018182  5.863636
      mon  0.000000  4.083333
      sat  0.000000  5.010000
      sun  0.000000  4.600000
      thu  0.000000  4.480000
      tue  0.000000  5.380000
      wed  0.000000  5.800000
may   fri  0.000000  4.000000
      sat  0.000000  4.900000
nov   tue  0.000000  4.500000
oct   fri  0.000000  5.400000
      mon  0.000000  4.350000
      sat  0.000000  2.800000
      sun  0.000000  3.000000
      tue  0.000000  2.700000
      wed  0.000000  3.150000
sep   fri  0.000000  3.910526
      mon  0.000000  3.107143
      sat  0.000000  3.460000
      sun  0.000000  3.955556
      thu  0.000000  3.357143
      tue  0.000000  3.431579
      wed  0.000000  3.378571

[64 rows x 2 columns]

In [55]:
import pandas as pd

pd.read_csv("/home/user-14/Desktop/data/desai.csv",sep=None,engine = 'python' )

     distributor_id distributor_retailer_code
0                 6                     P7786
1                 6                    P03095
2                 6                    P01088
3                 6                    P07508
4                 6                    P08300
5                 6                    P05780
6                 6                    P07391
7                 6                    P04875
8                 6                    P08950
9                 6                    P00762
10                6                     21092
11                6                     44135
12                6                     P1241
13                6                     P1234
14                6                    P07982
15                6                    P04358
16                6                     P0369
17                6                    P09890
18                6                    P04761
19                6                    P03890
20                6                    P03901
21                6                    P02956
22                6                    P02796
23                6                    P00988
24                6                    P00370
25                6                    P05056
26                6                    P01016
27                6                    P02489
28                6                     45086
29                6                    P01730
..              ...                       ...
270               6                    P04015
271               6                    P02995
272               6                    P07375
273               6                     P7798
274               6                    P03903
275               6                    P00226
276               6                    P05088
277               6                    P07617
278               6                    P09875
279               6                    P06585
280               6                    P01153
281               6                    P06894
282               6                    P02592
283               6                    P09852
284               6                    P04989
285               6                    P03959
286               6                    P07530
287               6                    P08596
288               6                    P07357
289               6                    P07845
290               6                    P05899
291               6                    P01415
292               6                    P09851
293               6                    P08119
294               6                    P05045
295               6                    P02548
296               6                    P02571
297               6                    P01289
298               6                    P04250
299               6                    P03633

[300 rows x 2 columns]

In [60]:
import pandas as pd
import PyPDF2

In [67]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
# print(#Type your code here.)

In [90]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
# print(round(#Type your code here))#Round off percentage values to 2 decimial places.
df

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23.0,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13.0,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26.0,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43.0,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35.0,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23.0,-47.64,6.15,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5.0,1.32,0.50,0.36
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48.0,1137.91,0.99,0.55
8,Ord_4725,Prod_13,SHP_6593,Cust_1641,162.0000,0.01,33.0,45.84,0.71,0.52
9,Ord_4725,Prod_6,SHP_6593,Cust_1641,57.2200,0.07,8.0,-27.72,6.60,0.37
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43.0,1675.98,0.99,0.56
11,Ord_1925,Prod_6,SHP_2637,Cust_708,465.9000,0.05,38.0,79.34,4.86,0.38
12,Ord_2978,Prod_16,SHP_4112,Cust_1088,305.0500,0.04,27.0,23.12,3.37,0.57
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15.0,-693.23,61.76,0.78
14,Ord_2207,Prod_10,SHP_3006,Cust_839,1410.9300,0.08,10.0,-317.48,36.09,0.77
15,Ord_2280,Prod_5,SHP_3114,Cust_839,460.6900,0.06,48.0,-103.48,7.29,0.45
16,Ord_2282,Prod_9,SHP_3122,Cust_839,443.4600,0.06,30.0,193.12,1.39,0.38
17,Ord_4471,Prod_15,SHP_6228,Cust_1521,13255.9300,0.02,25.0,4089.27,26.00,0.60
18,Ord_4427,Prod_6,SHP_6171,Cust_1521,283.1300,0.08,45.0,-141.26,6.81,0.36
19,Ord_996,Prod_13,SHP_1378,Cust_371,41.9700,0.05,12.0,-37.03,4.20,0.56
20,Ord_996,Prod_13,SHP_1378,Cust_371,57.1700,0.08,18.0,-24.03,2.31,0.56
21,Ord_996,Prod_6,SHP_1378,Cust_371,81.2500,0.01,11.0,-44.54,7.86,0.37
22,Ord_996,Prod_5,SHP_1377,Cust_371,3202.2500,0.09,44.0,991.26,19.99,0.43
23,Ord_996,Prod_7,SHP_1378,Cust_371,35.6400,0.05,10.0,-0.71,1.63,0.36
24,Ord_2573,Prod_3,SHP_3525,Cust_931,197.6100,0.08,13.0,3.46,7.27,0.38
25,Ord_2335,Prod_13,SHP_3204,Cust_931,38.2600,0.03,22.0,-2.34,0.70,0.56
26,Ord_2456,Prod_5,SHP_3367,Cust_931,109.5800,0.00,13.0,31.32,4.00,0.42
27,Ord_2405,Prod_9,SHP_3300,Cust_931,1062.6900,0.01,28.0,401.80,6.66,0.40
28,Ord_2573,Prod_4,SHP_3527,Cust_931,3594.7435,0.05,38.0,1016.97,2.50,0.55
29,Ord_2478,Prod_12,SHP_3395,Cust_931,139.9800,0.07,33.0,-140.54,6.89,0.39
...,...,...,...,...,...,...,...,...,...,...
8369,Ord_3633,Prod_3,SHP_5031,Cust_1274,1169.2600,0.02,41.0,515.62,1.49,0.38
8370,Ord_2696,Prod_13,SHP_3690,Cust_1006,62.7800,0.04,20.0,-17.75,2.03,0.57
8371,Ord_2624,Prod_4,SHP_3591,Cust_1006,4924.1350,0.07,28.0,1049.54,8.99,0.58
8372,Ord_2772,Prod_9,SHP_3806,Cust_1006,56.9000,0.03,7.0,12.64,1.39,0.36
8373,Ord_2600,Prod_16,SHP_3560,Cust_1006,106.6400,0.10,30.0,-31.95,1.32,0.83
8374,Ord_2658,Prod_5,SHP_3637,Cust_1006,1082.6600,0.08,14.0,-256.93,48.20,0.74
8375,Ord_2772,Prod_3,SHP_3806,Cust_1006,1413.8200,0.10,47.0,226.53,11.63,0.37
8376,Ord_2624,Prod_8,SHP_3590,Cust_1006,1211.0000,0.00,36.0,-27.99,6.50,0.79
8377,Ord_2722,Prod_12,SHP_3729,Cust_1006,34.0100,0.00,12.0,10.58,0.50,0.39
8378,Ord_2706,Prod_2,SHP_3705,Cust_1006,1361.9100,0.05,20.0,312.52,3.50,0.59
8379,Ord_2722,Prod_5,SHP_3730,Cust_1006,1008.9500,0.04,41.0,69.31,8.99,0.50
8380,Ord_2772,Prod_6,SHP_3807,Cust_1006,308.9200,0.04,45.0,-143.58,7.37,0.37
8381,Ord_2696,Prod_4,SHP_3691,Cust_1006,2836.0505,0.01,25.0,561.13,8.99,0.59
8382,Ord_2658,Prod_3,SHP_3636,Cust_1006,120.9800,0.00,28.0,-92.85,5.34,0.38
8383,Ord_2722,Prod_1,SHP_3731,Cust_1006,3508.3300,0.04,21.0,-546.98,35.00,0.85
8384,Ord_4620,Prod_3,SHP_6435,Cust_1577,59.6200,0.04,10.0,-56.30,7.78,0.37
8385,Ord_1833,Prod_3,SHP_2527,Cust_637,611.1600,0.04,46.0,100.22,4.98,0.40
8386,Ord_2324,Prod_7,SHP_3189,Cust_851,121.8700,0.07,39.0,11.32,1.35,0.40
8387,Ord_2220,Prod_3,SHP_3019,Cust_851,41.0600,0.04,4.0,-16.39,6.28,0.35
8388,Ord_4424,Prod_1,SHP_6165,Cust_1519,994.0400,0.03,10.0,-335.06,35.00,NaN
8389,Ord_4444,Prod_13,SHP_6192,Cust_1519,159.4100,0.00,44.0,34.68,0.98,0.52
8390,Ord_5435,Prod_16,SHP_7594,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN
8391,Ord_5435,Prod_4,SHP_7594,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN
8392,Ord_5384,Prod_9,SHP_7519,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN
8393,Ord_5348,Prod_8,SHP_7470,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
100*(df.isnull().sum()/len(df.index))

Ord_id                 0.000000
Prod_id                0.000000
Ship_id                0.000000
Cust_id                0.000000
Sales                  0.238124
Discount               0.654840
Order_Quantity         0.654840
Profit                 0.654840
Shipping_Cost          0.654840
Product_Base_Margin    1.297774
dtype: float64

In [103]:
df=df[df.isnull().sum(axis=1)<=5]
100*(df.isnull().sum()/len(df.index))

Ord_id                 0.000000
Prod_id                0.000000
Ship_id                0.000000
Cust_id                0.000000
Sales                  0.000000
Discount               0.417711
Order_Quantity         0.417711
Profit                 0.417711
Shipping_Cost          0.417711
Product_Base_Margin    1.062179
dtype: float64

In [143]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
# print(round(#Type your code here))#Round off percentage values to 2 decimial places.
# df

In [144]:
# df1=df[df["Product_Base_Margin"].isnull()]
# df1["Product_Base_Margin"].fillna(df["Product_Base_Margin"].mean())
mean_val=round(df["Product_Base_Margin"].mean(),2)
df.Product_Base_Margin=df.Product_Base_Margin.fillna(mean_val)
df

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23.0,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13.0,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26.0,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43.0,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35.0,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23.0,-47.64,6.15,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5.0,1.32,0.50,0.36
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48.0,1137.91,0.99,0.55
8,Ord_4725,Prod_13,SHP_6593,Cust_1641,162.0000,0.01,33.0,45.84,0.71,0.52
9,Ord_4725,Prod_6,SHP_6593,Cust_1641,57.2200,0.07,8.0,-27.72,6.60,0.37
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43.0,1675.98,0.99,0.56
11,Ord_1925,Prod_6,SHP_2637,Cust_708,465.9000,0.05,38.0,79.34,4.86,0.38
12,Ord_2978,Prod_16,SHP_4112,Cust_1088,305.0500,0.04,27.0,23.12,3.37,0.57
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15.0,-693.23,61.76,0.78
14,Ord_2207,Prod_10,SHP_3006,Cust_839,1410.9300,0.08,10.0,-317.48,36.09,0.77
15,Ord_2280,Prod_5,SHP_3114,Cust_839,460.6900,0.06,48.0,-103.48,7.29,0.45
16,Ord_2282,Prod_9,SHP_3122,Cust_839,443.4600,0.06,30.0,193.12,1.39,0.38
17,Ord_4471,Prod_15,SHP_6228,Cust_1521,13255.9300,0.02,25.0,4089.27,26.00,0.60
18,Ord_4427,Prod_6,SHP_6171,Cust_1521,283.1300,0.08,45.0,-141.26,6.81,0.36
19,Ord_996,Prod_13,SHP_1378,Cust_371,41.9700,0.05,12.0,-37.03,4.20,0.56
20,Ord_996,Prod_13,SHP_1378,Cust_371,57.1700,0.08,18.0,-24.03,2.31,0.56
21,Ord_996,Prod_6,SHP_1378,Cust_371,81.2500,0.01,11.0,-44.54,7.86,0.37
22,Ord_996,Prod_5,SHP_1377,Cust_371,3202.2500,0.09,44.0,991.26,19.99,0.43
23,Ord_996,Prod_7,SHP_1378,Cust_371,35.6400,0.05,10.0,-0.71,1.63,0.36
24,Ord_2573,Prod_3,SHP_3525,Cust_931,197.6100,0.08,13.0,3.46,7.27,0.38
25,Ord_2335,Prod_13,SHP_3204,Cust_931,38.2600,0.03,22.0,-2.34,0.70,0.56
26,Ord_2456,Prod_5,SHP_3367,Cust_931,109.5800,0.00,13.0,31.32,4.00,0.42
27,Ord_2405,Prod_9,SHP_3300,Cust_931,1062.6900,0.01,28.0,401.80,6.66,0.40
28,Ord_2573,Prod_4,SHP_3527,Cust_931,3594.7435,0.05,38.0,1016.97,2.50,0.55
29,Ord_2478,Prod_12,SHP_3395,Cust_931,139.9800,0.07,33.0,-140.54,6.89,0.39
...,...,...,...,...,...,...,...,...,...,...
8369,Ord_3633,Prod_3,SHP_5031,Cust_1274,1169.2600,0.02,41.0,515.62,1.49,0.38
8370,Ord_2696,Prod_13,SHP_3690,Cust_1006,62.7800,0.04,20.0,-17.75,2.03,0.57
8371,Ord_2624,Prod_4,SHP_3591,Cust_1006,4924.1350,0.07,28.0,1049.54,8.99,0.58
8372,Ord_2772,Prod_9,SHP_3806,Cust_1006,56.9000,0.03,7.0,12.64,1.39,0.36
8373,Ord_2600,Prod_16,SHP_3560,Cust_1006,106.6400,0.10,30.0,-31.95,1.32,0.83
8374,Ord_2658,Prod_5,SHP_3637,Cust_1006,1082.6600,0.08,14.0,-256.93,48.20,0.74
8375,Ord_2772,Prod_3,SHP_3806,Cust_1006,1413.8200,0.10,47.0,226.53,11.63,0.37
8376,Ord_2624,Prod_8,SHP_3590,Cust_1006,1211.0000,0.00,36.0,-27.99,6.50,0.79
8377,Ord_2722,Prod_12,SHP_3729,Cust_1006,34.0100,0.00,12.0,10.58,0.50,0.39
8378,Ord_2706,Prod_2,SHP_3705,Cust_1006,1361.9100,0.05,20.0,312.52,3.50,0.59
8379,Ord_2722,Prod_5,SHP_3730,Cust_1006,1008.9500,0.04,41.0,69.31,8.99,0.50
8380,Ord_2772,Prod_6,SHP_3807,Cust_1006,308.9200,0.04,45.0,-143.58,7.37,0.37
8381,Ord_2696,Prod_4,SHP_3691,Cust_1006,2836.0505,0.01,25.0,561.13,8.99,0.59
8382,Ord_2658,Prod_3,SHP_3636,Cust_1006,120.9800,0.00,28.0,-92.85,5.34,0.38
8383,Ord_2722,Prod_1,SHP_3731,Cust_1006,3508.3300,0.04,21.0,-546.98,35.00,0.85
8384,Ord_4620,Prod_3,SHP_6435,Cust_1577,59.6200,0.04,10.0,-56.30,7.78,0.37
8385,Ord_1833,Prod_3,SHP_2527,Cust_637,611.1600,0.04,46.0,100.22,4.98,0.40
8386,Ord_2324,Prod_7,SHP_3189,Cust_851,121.8700,0.07,39.0,11.32,1.35,0.40
8387,Ord_2220,Prod_3,SHP_3019,Cust_851,41.0600,0.04,4.0,-16.39,6.28,0.35
8388,Ord_4424,Prod_1,SHP_6165,Cust_1519,994.0400,0.03,10.0,-335.06,35.00,0.51
8389,Ord_4444,Prod_13,SHP_6192,Cust_1519,159.4100,0.00,44.0,34.68,0.98,0.52
8390,Ord_5435,Prod_16,SHP_7594,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51
8391,Ord_5435,Prod_4,SHP_7594,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51
8392,Ord_5384,Prod_9,SHP_7519,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51
8393,Ord_5348,Prod_8,SHP_7470,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,NaN,NaN,NaN,NaN,NaN,0.51